### PR TITLE
Go redigo more similar to Crystal version

### PR DESCRIPTION
**Pull request by dansouza**
Please refer to https://github.com/stefanwille/redis-client-benchmarks/commit/87ffea7dfb8bf218e9958e08080f321b2d882cb6 for explanation.

### CODE REVIEW

**Comment by sergeylanzman** [comment]
:+1:

**Comment by stefanwille** [comment]
Thanks for the PR. I just read it and I must say that it doesn't reflect what the Crystal version does. It sends the requests without receiving the responses, other than Crystal-Redis.

**Comment by dansouza** [comment]
@stefanwille but I think that's exactly what the Crystal version is doing [if you look here](https://github.com/stefanwille/redis-client-benchmarks/blob/master/Crystal/crystal_redis_performance.cr#L8)  -- it is calling pipeline.set() but never reads any reply back (unless the reading is done under the hood on pipeline.set()). Go should also make SETs but never read anything back (or Crystal should read stuff back) so they are fair comparisons. Other than that, there's still the issue of the Go version looping 1.6M times where the Crystal version only loops 1M times.

**Comment by stefanwille** [comment]
@dansouza the Crystal version reads all replies back implicitely because crystal-redis does it for the caller. The code in crystal-redis which does this is in https://github.com/stefanwille/crystal-redis/blob/master/src/redis/strategy/pipeline.cr#L21-L27

**Comment by dansouza** [comment]
Got it, you're right - the Go version is still not exactly an apples-to-apples comparison because you're calling an extra function for every value received (errorHandler()) but I'll assume that the Crystal version also does the same implicitly somewhere. I'm closing this pull request and creating another one with just a fix to the upper limit of the loop.

**Pull request closed without merging**
